version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yoshikawa-river"
    labels:
      - "dependencies"
      - "python"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "coverage*"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "yoshikawa-river"
    labels:
      - "dependencies"
      - "github-actions"
      
  # Docker
  - package-ecosystem: "docker"
    directory: "/docker/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "yoshikawa-river"
    labels:
      - "dependencies"
      - "docker"