# Configuration for PR labeler

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'

python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - 'requirements*.txt'
      - 'pyproject.toml'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - '**/test_*.py'
      - '**/*_test.py'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/*.yml'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - 'docker/**'
      - 'docker-compose.yml'
      - 'Dockerfile'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'alembic/**'
      - '**/models/**'
      - '**/migrations/**'

frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'streamlit/**'
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
