codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  
  status:
    project:
      default:
        target: 60%
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "**/migrations/**/*"
  - "**/__pycache__/**/*"
  - "src/api/schemas/**/*"