repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml

  # MyPyは一時的に無効化（types-allパッケージの問題）
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.14.0
  #   hooks:
  #     - id: mypy
  #       args: [--config-file, mypy.ini]
  #       additional_dependencies: [types-all]
  #       exclude: ^(tests/|scripts/|alembic/)
