"""初期マイグレーション

Revision ID: 5f8bb49cd9e1
Revises: 
Create Date: 2025-08-02 01:16:13.197383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f8bb49cd9e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MLflowテーブルの削除（存在する場合のみ）
    try:
        op.drop_index('name', table_name='mlflow_experiments')
    except Exception:
        pass  # インデックスが存在しない場合は無視
    
    try:
        op.drop_table('mlflow_experiments')
    except Exception:
        pass  # テーブルが存在しない場合は無視
    
    # feature_cacheテーブルの操作（存在しない場合はスキップ）
    from sqlalchemy import inspect
    from sqlalchemy.engine import reflection
    
    # コネクションを取得してテーブル存在確認
    bind = op.get_bind()
    try:
        inspector = reflection.Inspector.from_engine(bind)
        tables = inspector.get_table_names()
    except Exception:
        # テーブル一覧取得に失敗した場合は空として扱う
        tables = []
    
    if 'feature_cache' in tables:
        try:
            op.add_column('feature_cache', sa.Column('created_at', sa.DateTime(), nullable=False))
            op.add_column('feature_cache', sa.Column('updated_at', sa.DateTime(), nullable=False))
        except Exception:
            pass  # カラムが既に存在する場合は無視
        
        try:
            op.alter_column('feature_cache', 'race_id',
                       existing_type=mysql.INTEGER(),
                       nullable=False,
                       comment='レースID')
            op.alter_column('feature_cache', 'horse_id',
                       existing_type=mysql.INTEGER(),
                       nullable=False,
                       comment='馬ID')
            op.alter_column('feature_cache', 'feature_type',
                       existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
                       comment='特徴量タイプ',
                       existing_nullable=False)
            op.alter_column('feature_cache', 'feature_data',
                       existing_type=mysql.JSON(),
                       comment='特徴量データ（JSON形式）',
                       existing_nullable=False)
            op.alter_column('feature_cache', 'calculated_at',
                       existing_type=mysql.TIMESTAMP(),
                       server_default=None,
                       type_=sa.DateTime(),
                       nullable=False,
                       comment='計算日時')
            op.alter_column('feature_cache', 'expires_at',
                       existing_type=mysql.TIMESTAMP(),
                       type_=sa.DateTime(),
                       comment='有効期限',
                       existing_nullable=True)
        except Exception:
            pass  # エラーが発生した場合は無視
        
        try:
            op.drop_constraint('feature_cache_ibfk_2', 'feature_cache', type_='foreignkey')
            op.drop_constraint('feature_cache_ibfk_1', 'feature_cache', type_='foreignkey')
        except Exception:
            pass  # 制約が存在しない場合は無視
            
        try:
            op.create_foreign_key(None, 'feature_cache', 'races', ['race_id'], ['id'], ondelete='CASCADE')
            op.create_foreign_key(None, 'feature_cache', 'horses', ['horse_id'], ['id'], ondelete='CASCADE')
        except Exception:
            pass  # 外部キーの作成に失敗した場合は無視
    op.alter_column('horses', 'horse_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='馬ID',
               existing_nullable=False)
    op.alter_column('horses', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='馬名',
               existing_nullable=False)
    op.alter_column('horses', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='馬名（カナ）',
               existing_nullable=True)
    op.alter_column('horses', 'sex',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='性別 (牡/牝/セ)',
               existing_nullable=False)
    op.alter_column('horses', 'birth_date',
               existing_type=sa.DATE(),
               comment='生年月日',
               existing_nullable=True)
    op.alter_column('horses', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='毛色',
               existing_nullable=True)
    op.alter_column('horses', 'father_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='父馬名',
               existing_nullable=True)
    op.alter_column('horses', 'mother_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='母馬名',
               existing_nullable=True)
    op.alter_column('horses', 'mother_father_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='母父馬名',
               existing_nullable=True)
    op.alter_column('horses', 'owner_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='馬主名',
               existing_nullable=True)
    op.alter_column('horses', 'trainer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='調教師名',
               existing_nullable=True)
    op.alter_column('horses', 'breeding_farm',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='生産牧場',
               existing_nullable=True)
    op.alter_column('horses', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('horses', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('jockeys', 'jockey_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='騎手ID',
               existing_nullable=False)
    op.alter_column('jockeys', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='騎手名',
               existing_nullable=False)
    op.alter_column('jockeys', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='騎手名（カナ）',
               existing_nullable=True)
    op.alter_column('jockeys', 'birth_date',
               existing_type=sa.DATE(),
               comment='生年月日',
               existing_nullable=True)
    op.alter_column('jockeys', 'license_date',
               existing_type=sa.DATE(),
               comment='免許取得日',
               existing_nullable=True)
    op.alter_column('jockeys', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('jockeys', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.add_column('odds_history', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('odds_history', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='レースID')
    op.alter_column('odds_history', 'horse_number',
               existing_type=mysql.INTEGER(),
               comment='馬番',
               existing_nullable=False)
    op.alter_column('odds_history', 'odds_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='オッズ種別 (win/place/quinella/etc)',
               existing_nullable=False)
    op.alter_column('odds_history', 'odds_value',
               existing_type=mysql.DECIMAL(precision=8, scale=1),
               comment='オッズ値',
               existing_nullable=False)
    op.alter_column('odds_history', 'recorded_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='記録日時',
               existing_nullable=False)
    op.alter_column('odds_history', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('odds_history_ibfk_1', 'odds_history', type_='foreignkey')
    op.create_foreign_key(None, 'odds_history', 'races', ['race_id'], ['id'], ondelete='CASCADE')
    op.add_column('predictions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('predictions', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='レースID')
    op.alter_column('predictions', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='モデル名',
               existing_nullable=False)
    op.alter_column('predictions', 'model_version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='モデルバージョン',
               existing_nullable=True)
    op.alter_column('predictions', 'prediction_data',
               existing_type=mysql.JSON(),
               comment='予測結果の詳細（JSON形式）',
               existing_nullable=False)
    op.alter_column('predictions', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('predictions_ibfk_1', 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'races', ['race_id'], ['id'], ondelete='CASCADE')
    op.alter_column('race_entries', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='レースID')
    op.alter_column('race_entries', 'horse_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='馬ID')
    op.alter_column('race_entries', 'post_position',
               existing_type=mysql.INTEGER(),
               comment='枠番',
               existing_nullable=False)
    op.alter_column('race_entries', 'horse_number',
               existing_type=mysql.INTEGER(),
               comment='馬番',
               existing_nullable=False)
    op.alter_column('race_entries', 'jockey_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='騎手ID')
    op.alter_column('race_entries', 'trainer_id',
               existing_type=mysql.INTEGER(),
               comment='調教師ID',
               existing_nullable=True)
    op.alter_column('race_entries', 'weight_carried',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               comment='斤量',
               existing_nullable=False)
    op.alter_column('race_entries', 'horse_weight',
               existing_type=mysql.INTEGER(),
               comment='馬体重',
               existing_nullable=True)
    op.alter_column('race_entries', 'horse_weight_diff',
               existing_type=mysql.INTEGER(),
               comment='馬体重増減',
               existing_nullable=True)
    op.alter_column('race_entries', 'age',
               existing_type=mysql.INTEGER(),
               comment='年齢',
               existing_nullable=False)
    op.alter_column('race_entries', 'odds_win',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment='単勝オッズ',
               existing_nullable=True)
    op.alter_column('race_entries', 'odds_place_min',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment='複勝オッズ（最小）',
               existing_nullable=True)
    op.alter_column('race_entries', 'odds_place_max',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment='複勝オッズ（最大）',
               existing_nullable=True)
    op.alter_column('race_entries', 'popularity',
               existing_type=mysql.INTEGER(),
               comment='人気順位',
               existing_nullable=True)
    op.alter_column('race_entries', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('race_entries', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('race_entries_ibfk_2', 'race_entries', type_='foreignkey')
    op.drop_constraint('race_entries_ibfk_1', 'race_entries', type_='foreignkey')
    op.create_foreign_key(None, 'race_entries', 'races', ['race_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'race_entries', 'horses', ['horse_id'], ['id'], ondelete='CASCADE')
    op.alter_column('race_results', 'race_entry_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='出走情報ID')
    op.alter_column('race_results', 'finish_position',
               existing_type=mysql.INTEGER(),
               comment='着順',
               existing_nullable=True)
    op.alter_column('race_results', 'finish_time',
               existing_type=mysql.TIME(),
               comment='タイム',
               existing_nullable=True)
    op.alter_column('race_results', 'last_3f_time',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               comment='上がり3ハロン',
               existing_nullable=True)
    op.alter_column('race_results', 'corner_positions',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='通過順位',
               existing_nullable=True)
    op.alter_column('race_results', 'remarks',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='備考',
               existing_nullable=True)
    op.alter_column('race_results', 'prize_money',
               existing_type=mysql.INTEGER(),
               comment='獲得賞金',
               existing_nullable=True)
    op.alter_column('race_results', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('race_results', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('race_results_ibfk_1', 'race_results', type_='foreignkey')
    op.create_foreign_key(None, 'race_results', 'race_entries', ['race_entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('racecourses', 'jra_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               comment='JRAコード',
               existing_nullable=False)
    op.alter_column('racecourses', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='競馬場名',
               existing_nullable=False)
    op.alter_column('racecourses', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='競馬場名（カナ）',
               existing_nullable=True)
    op.alter_column('racecourses', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='所在地',
               existing_nullable=True)
    op.alter_column('racecourses', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('racecourses', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('races', 'race_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='レースキー (YYYYMMDDRRNN)',
               existing_nullable=False)
    op.alter_column('races', 'race_date',
               existing_type=sa.DATE(),
               comment='開催日',
               existing_nullable=False)
    op.alter_column('races', 'racecourse_id',
               existing_type=mysql.INTEGER(),
               comment='競馬場ID',
               existing_nullable=True)
    op.alter_column('races', 'race_number',
               existing_type=mysql.INTEGER(),
               comment='R数',
               existing_nullable=False)
    op.alter_column('races', 'race_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='レース名',
               existing_nullable=False)
    op.alter_column('races', 'race_name_sub',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='レース名（サブ）',
               existing_nullable=True)
    op.alter_column('races', 'grade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='グレード (G1, G2, G3, OP, etc)',
               existing_nullable=True)
    op.alter_column('races', 'race_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='トラックタイプ (芝/ダート)',
               existing_nullable=False)
    op.alter_column('races', 'distance',
               existing_type=mysql.INTEGER(),
               comment='距離（メートル）',
               existing_nullable=False)
    op.alter_column('races', 'direction',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='回り (右/左/直線)',
               existing_nullable=True)
    op.alter_column('races', 'weather',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='天候',
               existing_nullable=True)
    op.alter_column('races', 'track_condition',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='馬場状態',
               existing_nullable=True)
    op.alter_column('races', 'prize_money',
               existing_type=mysql.JSON(),
               comment='賞金情報（JSON形式）',
               existing_nullable=True)
    op.alter_column('races', 'entry_count',
               existing_type=mysql.INTEGER(),
               comment='出走頭数',
               existing_nullable=True)
    op.alter_column('races', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('races', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('trainers', 'trainer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='調教師ID',
               existing_nullable=False)
    op.alter_column('trainers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='調教師名',
               existing_nullable=False)
    op.alter_column('trainers', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='調教師名（カナ）',
               existing_nullable=True)
    op.alter_column('trainers', 'belonging',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='所属 (美浦/栗東)',
               existing_nullable=True)
    op.alter_column('trainers', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('trainers', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainers', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('trainers', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('trainers', 'belonging',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='所属 (美浦/栗東)',
               existing_nullable=True)
    op.alter_column('trainers', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='調教師名（カナ）',
               existing_nullable=True)
    op.alter_column('trainers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='調教師名',
               existing_nullable=False)
    op.alter_column('trainers', 'trainer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='調教師ID',
               existing_nullable=False)
    op.alter_column('races', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('races', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('races', 'entry_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='出走頭数',
               existing_nullable=True)
    op.alter_column('races', 'prize_money',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='賞金情報（JSON形式）',
               existing_nullable=True)
    op.alter_column('races', 'track_condition',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='馬場状態',
               existing_nullable=True)
    op.alter_column('races', 'weather',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='天候',
               existing_nullable=True)
    op.alter_column('races', 'direction',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='回り (右/左/直線)',
               existing_nullable=True)
    op.alter_column('races', 'distance',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='距離（メートル）',
               existing_nullable=False)
    op.alter_column('races', 'race_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='トラックタイプ (芝/ダート)',
               existing_nullable=False)
    op.alter_column('races', 'grade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='グレード (G1, G2, G3, OP, etc)',
               existing_nullable=True)
    op.alter_column('races', 'race_name_sub',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='レース名（サブ）',
               existing_nullable=True)
    op.alter_column('races', 'race_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='レース名',
               existing_nullable=False)
    op.alter_column('races', 'race_number',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='R数',
               existing_nullable=False)
    op.alter_column('races', 'racecourse_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='競馬場ID',
               existing_nullable=True)
    op.alter_column('races', 'race_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='開催日',
               existing_nullable=False)
    op.alter_column('races', 'race_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='レースキー (YYYYMMDDRRNN)',
               existing_nullable=False)
    op.alter_column('racecourses', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('racecourses', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('racecourses', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='所在地',
               existing_nullable=True)
    op.alter_column('racecourses', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='競馬場名（カナ）',
               existing_nullable=True)
    op.alter_column('racecourses', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='競馬場名',
               existing_nullable=False)
    op.alter_column('racecourses', 'jra_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               comment=None,
               existing_comment='JRAコード',
               existing_nullable=False)
    op.drop_constraint(None, 'race_results', type_='foreignkey')
    op.create_foreign_key('race_results_ibfk_1', 'race_results', 'race_entries', ['race_entry_id'], ['id'])
    op.alter_column('race_results', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('race_results', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('race_results', 'prize_money',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='獲得賞金',
               existing_nullable=True)
    op.alter_column('race_results', 'remarks',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='備考',
               existing_nullable=True)
    op.alter_column('race_results', 'corner_positions',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='通過順位',
               existing_nullable=True)
    op.alter_column('race_results', 'last_3f_time',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               comment=None,
               existing_comment='上がり3ハロン',
               existing_nullable=True)
    op.alter_column('race_results', 'finish_time',
               existing_type=mysql.TIME(),
               comment=None,
               existing_comment='タイム',
               existing_nullable=True)
    op.alter_column('race_results', 'finish_position',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='着順',
               existing_nullable=True)
    op.alter_column('race_results', 'race_entry_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='出走情報ID')
    op.drop_constraint(None, 'race_entries', type_='foreignkey')
    op.drop_constraint(None, 'race_entries', type_='foreignkey')
    op.create_foreign_key('race_entries_ibfk_1', 'race_entries', 'races', ['race_id'], ['id'])
    op.create_foreign_key('race_entries_ibfk_2', 'race_entries', 'horses', ['horse_id'], ['id'])
    op.alter_column('race_entries', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('race_entries', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('race_entries', 'popularity',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='人気順位',
               existing_nullable=True)
    op.alter_column('race_entries', 'odds_place_max',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment=None,
               existing_comment='複勝オッズ（最大）',
               existing_nullable=True)
    op.alter_column('race_entries', 'odds_place_min',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment=None,
               existing_comment='複勝オッズ（最小）',
               existing_nullable=True)
    op.alter_column('race_entries', 'odds_win',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment=None,
               existing_comment='単勝オッズ',
               existing_nullable=True)
    op.alter_column('race_entries', 'age',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='年齢',
               existing_nullable=False)
    op.alter_column('race_entries', 'horse_weight_diff',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='馬体重増減',
               existing_nullable=True)
    op.alter_column('race_entries', 'horse_weight',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='馬体重',
               existing_nullable=True)
    op.alter_column('race_entries', 'weight_carried',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               comment=None,
               existing_comment='斤量',
               existing_nullable=False)
    op.alter_column('race_entries', 'trainer_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='調教師ID',
               existing_nullable=True)
    op.alter_column('race_entries', 'jockey_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='騎手ID')
    op.alter_column('race_entries', 'horse_number',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='馬番',
               existing_nullable=False)
    op.alter_column('race_entries', 'post_position',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='枠番',
               existing_nullable=False)
    op.alter_column('race_entries', 'horse_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='馬ID')
    op.alter_column('race_entries', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='レースID')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key('predictions_ibfk_1', 'predictions', 'races', ['race_id'], ['id'])
    op.alter_column('predictions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('predictions', 'prediction_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='予測結果の詳細（JSON形式）',
               existing_nullable=False)
    op.alter_column('predictions', 'model_version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='モデルバージョン',
               existing_nullable=True)
    op.alter_column('predictions', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='モデル名',
               existing_nullable=False)
    op.alter_column('predictions', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='レースID')
    op.drop_column('predictions', 'updated_at')
    op.drop_constraint(None, 'odds_history', type_='foreignkey')
    op.create_foreign_key('odds_history_ibfk_1', 'odds_history', 'races', ['race_id'], ['id'])
    op.alter_column('odds_history', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('odds_history', 'recorded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='記録日時',
               existing_nullable=False)
    op.alter_column('odds_history', 'odds_value',
               existing_type=mysql.DECIMAL(precision=8, scale=1),
               comment=None,
               existing_comment='オッズ値',
               existing_nullable=False)
    op.alter_column('odds_history', 'odds_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='オッズ種別 (win/place/quinella/etc)',
               existing_nullable=False)
    op.alter_column('odds_history', 'horse_number',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='馬番',
               existing_nullable=False)
    op.alter_column('odds_history', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='レースID')
    op.drop_column('odds_history', 'updated_at')
    op.alter_column('jockeys', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jockeys', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jockeys', 'license_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='免許取得日',
               existing_nullable=True)
    op.alter_column('jockeys', 'birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生年月日',
               existing_nullable=True)
    op.alter_column('jockeys', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='騎手名（カナ）',
               existing_nullable=True)
    op.alter_column('jockeys', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='騎手名',
               existing_nullable=False)
    op.alter_column('jockeys', 'jockey_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='騎手ID',
               existing_nullable=False)
    op.alter_column('horses', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('horses', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('horses', 'breeding_farm',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='生産牧場',
               existing_nullable=True)
    op.alter_column('horses', 'trainer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='調教師名',
               existing_nullable=True)
    op.alter_column('horses', 'owner_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='馬主名',
               existing_nullable=True)
    op.alter_column('horses', 'mother_father_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='母父馬名',
               existing_nullable=True)
    op.alter_column('horses', 'mother_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='母馬名',
               existing_nullable=True)
    op.alter_column('horses', 'father_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='父馬名',
               existing_nullable=True)
    op.alter_column('horses', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='毛色',
               existing_nullable=True)
    op.alter_column('horses', 'birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生年月日',
               existing_nullable=True)
    op.alter_column('horses', 'sex',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='性別 (牡/牝/セ)',
               existing_nullable=False)
    op.alter_column('horses', 'name_kana',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='馬名（カナ）',
               existing_nullable=True)
    op.alter_column('horses', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='馬名',
               existing_nullable=False)
    op.alter_column('horses', 'horse_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='馬ID',
               existing_nullable=False)
    op.drop_constraint(None, 'feature_cache', type_='foreignkey')
    op.drop_constraint(None, 'feature_cache', type_='foreignkey')
    op.create_foreign_key('feature_cache_ibfk_1', 'feature_cache', 'races', ['race_id'], ['id'])
    op.create_foreign_key('feature_cache_ibfk_2', 'feature_cache', 'horses', ['horse_id'], ['id'])
    op.alter_column('feature_cache', 'expires_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='有効期限',
               existing_nullable=True)
    op.alter_column('feature_cache', 'calculated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='計算日時')
    op.alter_column('feature_cache', 'feature_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='特徴量データ（JSON形式）',
               existing_nullable=False)
    op.alter_column('feature_cache', 'feature_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='特徴量タイプ',
               existing_nullable=False)
    op.alter_column('feature_cache', 'horse_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='馬ID')
    op.alter_column('feature_cache', 'race_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='レースID')
    op.drop_column('feature_cache', 'updated_at')
    op.drop_column('feature_cache', 'created_at')
    op.create_table('mlflow_experiments',
    sa.Column('experiment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('artifact_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('lifecycle_stage', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('creation_time', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update_time', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('experiment_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'mlflow_experiments', ['name'], unique=True)
    # ### end Alembic commands ###