"""初期マイグレーション

Revision ID: 5f8bb49cd9e1
Revises: 
Create Date: 2025-08-02 01:16:13.197383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f8bb49cd9e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racecourses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jra_code', sa.String(length=2), nullable=False, comment='JRAコード'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='競馬場名'),
    sa.Column('name_kana', sa.String(length=100), nullable=True, comment='競馬場名（カナ）'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='所在地'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jra_code')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.String(length=10), nullable=False, comment='馬ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='馬名'),
    sa.Column('name_kana', sa.String(length=100), nullable=True, comment='馬名（カナ）'),
    sa.Column('sex', sa.String(length=10), nullable=False, comment='性別 (牡/牝/セ)'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='生年月日'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='毛色'),
    sa.Column('father_name', sa.String(length=50), nullable=True, comment='父馬名'),
    sa.Column('mother_name', sa.String(length=50), nullable=True, comment='母馬名'),
    sa.Column('mother_father_name', sa.String(length=50), nullable=True, comment='母父馬名'),
    sa.Column('owner_name', sa.String(length=100), nullable=True, comment='馬主名'),
    sa.Column('trainer_name', sa.String(length=50), nullable=True, comment='調教師名'),
    sa.Column('breeding_farm', sa.String(length=100), nullable=True, comment='生産牧場'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horse_id')
    )
    op.create_index('idx_name', 'horses', ['name'], unique=False)
    op.create_index('idx_name_fulltext', 'horses', ['name'], unique=False)
    op.create_table('jockeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jockey_id', sa.String(length=10), nullable=False, comment='騎手ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='騎手名'),
    sa.Column('name_kana', sa.String(length=100), nullable=True, comment='騎手名（カナ）'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='生年月日'),
    sa.Column('license_date', sa.Date(), nullable=True, comment='免許取得日'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jockey_id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.String(length=10), nullable=False, comment='調教師ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='調教師名'),
    sa.Column('name_kana', sa.String(length=100), nullable=True, comment='調教師名（カナ）'),
    sa.Column('belonging', sa.String(length=20), nullable=True, comment='所属 (美浦/栗東)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_key', sa.String(length=20), nullable=False, comment='レースキー (YYYYMMDDRRNN)'),
    sa.Column('race_date', sa.Date(), nullable=False, comment='開催日'),
    sa.Column('racecourse_id', sa.Integer(), nullable=True, comment='競馬場ID'),
    sa.Column('race_number', sa.Integer(), nullable=False, comment='R数'),
    sa.Column('race_name', sa.String(length=100), nullable=False, comment='レース名'),
    sa.Column('race_name_sub', sa.String(length=100), nullable=True, comment='レース名（サブ）'),
    sa.Column('grade', sa.String(length=10), nullable=True, comment='グレード (G1, G2, G3, OP, etc)'),
    sa.Column('race_type', sa.String(length=10), nullable=False, comment='トラックタイプ (芝/ダート)'),
    sa.Column('distance', sa.Integer(), nullable=False, comment='距離（メートル）'),
    sa.Column('direction', sa.String(length=10), nullable=True, comment='回り (右/左/直線)'),
    sa.Column('weather', sa.String(length=10), nullable=True, comment='天候'),
    sa.Column('track_condition', sa.String(length=10), nullable=True, comment='馬場状態'),
    sa.Column('prize_money', sa.JSON(), nullable=True, comment='賞金情報（JSON形式）'),
    sa.Column('entry_count', sa.Integer(), nullable=True, comment='出走頭数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['racecourse_id'], ['racecourses.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_key')
    )
    op.create_index('idx_grade', 'races', ['grade'], unique=False)
    op.create_index('idx_race_date', 'races', ['race_date'], unique=False)
    op.create_index('idx_racecourse_id', 'races', ['racecourse_id'], unique=False)
    op.create_table('feature_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False, comment='レースID'),
    sa.Column('horse_id', sa.Integer(), nullable=False, comment='馬ID'),
    sa.Column('feature_type', sa.String(length=50), nullable=False, comment='特徴量タイプ'),
    sa.Column('feature_data', sa.JSON(), nullable=False, comment='特徴量データ（JSON形式）'),
    sa.Column('calculated_at', sa.DateTime(), nullable=False, comment='計算日時'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='有効期限'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_id', 'feature_type', name='unique_feature')
    )
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False, comment='レースID'),
    sa.Column('horse_number', sa.Integer(), nullable=False, comment='馬番'),
    sa.Column('odds_type', sa.String(length=20), nullable=False, comment='オッズ種別 (win/place/quinella/etc)'),
    sa.Column('odds_value', sa.Numeric(precision=8, scale=1), nullable=False, comment='オッズ値'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False, comment='記録日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_race_time', 'odds_history', ['race_id', 'recorded_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False, comment='レースID'),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='モデル名'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='モデルバージョン'),
    sa.Column('prediction_data', sa.JSON(), nullable=False, comment='予測結果の詳細（JSON形式）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_race_model', 'predictions', ['race_id', 'model_name'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False, comment='レースID'),
    sa.Column('horse_id', sa.Integer(), nullable=False, comment='馬ID'),
    sa.Column('post_position', sa.Integer(), nullable=False, comment='枠番'),
    sa.Column('horse_number', sa.Integer(), nullable=False, comment='馬番'),
    sa.Column('jockey_id', sa.Integer(), nullable=False, comment='騎手ID'),
    sa.Column('trainer_id', sa.Integer(), nullable=True, comment='調教師ID'),
    sa.Column('weight_carried', sa.Numeric(precision=4, scale=1), nullable=False, comment='斤量'),
    sa.Column('horse_weight', sa.Integer(), nullable=True, comment='馬体重'),
    sa.Column('horse_weight_diff', sa.Integer(), nullable=True, comment='馬体重増減'),
    sa.Column('age', sa.Integer(), nullable=False, comment='年齢'),
    sa.Column('odds_win', sa.Numeric(precision=6, scale=1), nullable=True, comment='単勝オッズ'),
    sa.Column('odds_place_min', sa.Numeric(precision=6, scale=1), nullable=True, comment='複勝オッズ（最小）'),
    sa.Column('odds_place_max', sa.Numeric(precision=6, scale=1), nullable=True, comment='複勝オッズ（最大）'),
    sa.Column('popularity', sa.Integer(), nullable=True, comment='人気順位'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_number', name='unique_race_horse')
    )
    op.create_index('idx_horse_id', 'race_entries', ['horse_id'], unique=False)
    op.create_index('idx_jockey_id', 'race_entries', ['jockey_id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_entry_id', sa.Integer(), nullable=False, comment='出走情報ID'),
    sa.Column('finish_position', sa.Integer(), nullable=True, comment='着順'),
    sa.Column('finish_time', sa.Time(), nullable=True, comment='タイム'),
    sa.Column('last_3f_time', sa.Numeric(precision=4, scale=1), nullable=True, comment='上がり3ハロン'),
    sa.Column('corner_positions', sa.String(length=20), nullable=True, comment='通過順位'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='備考'),
    sa.Column('prize_money', sa.Integer(), nullable=True, comment='獲得賞金'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_entry_id')
    )
    op.create_index('idx_finish_position', 'race_results', ['finish_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_finish_position', table_name='race_results')
    op.drop_table('race_results')
    op.drop_index('idx_jockey_id', table_name='race_entries')
    op.drop_index('idx_horse_id', table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index('idx_race_model', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_race_time', table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_table('feature_cache')
    op.drop_index('idx_racecourse_id', table_name='races')
    op.drop_index('idx_race_date', table_name='races')
    op.drop_index('idx_grade', table_name='races')
    op.drop_table('races')
    op.drop_table('trainers')
    op.drop_table('jockeys')
    op.drop_index('idx_name_fulltext', table_name='horses')
    op.drop_index('idx_name', table_name='horses')
    op.drop_table('horses')
    op.drop_table('racecourses')
    # ### end Alembic commands ###