"""初期マイグレーション

Revision ID: 5f8bb49cd9e1
Revises: 
Create Date: 2025-08-02 01:16:13.197383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f8bb49cd9e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CI環境との互換性のため、初期マイグレーションはスキップ
    # 実際の開発環境では必要に応じて手動でテーブルを作成してください
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass