-- mykeibaDB互換スキーマ初期化スクリプト
-- 競馬予想AIシステム用データベーススキーマ（実際のmykeibaDB形式）

-- データベース作成（docker-composeで作成済みの場合はスキップ）
-- CREATE DATABASE IF NOT EXISTS keiba_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE keiba_db;

-- ========================================
-- mykeibaDB標準テーブル（実際のスキーマ）
-- ========================================

-- RACE_SHOSAI（レース詳細）
CREATE TABLE IF NOT EXISTS RACE_SHOSAI (
    INSERT_TIMESTAMP CHAR(19),
    UPDATE_TIMESTAMP CHAR(19),
    RECORD_SHUBETSU_ID CHAR(2),
    DATA_KUBUN CHAR(1),
    DATA_SAKUSEI_NENGAPPI CHAR(8),
    RACE_CODE CHAR(16) PRIMARY KEY,
    KAISAI_NEN CHAR(4),
    KAISAI_GAPPI CHAR(4),
    KEIBAJO_CODE CHAR(2),
    KAISAI_KAI CHAR(2),
    KAISAI_NICHIME CHAR(2),
    RACE_BANGO CHAR(2),
    YOBI_CODE CHAR(1),
    TOKUBETSU_KYOSO_BANGO CHAR(4),
    KYOSOMEI_HONDAI VARCHAR(60),
    KYOSOMEI_FUKUDAI VARCHAR(60),
    KYOSOMEI_KAKKONAI VARCHAR(60),
    KYOSOMEI_HONDAI_ENG VARCHAR(120),
    KYOSOMEI_FUKUDAI_ENG VARCHAR(120),
    KYOSOMEI_KAKKONAI_ENG VARCHAR(120),
    KYOSOMEI_RYAKUSHO_10 VARCHAR(20),
    KYOSOMEI_RYAKUSHO_6 VARCHAR(12),
    KYOSOMEI_RYAKUSHO_3 VARCHAR(6),
    KYOSOMEI_KUBUN CHAR(1),
    JUSHO_KAIJI CHAR(3),
    GRADE_CODE CHAR(1),
    HENKOMAE_GRADE_CODE CHAR(1),
    KYOSO_SHUBETSU_CODE CHAR(2),
    KYOSO_KIGO_CODE CHAR(3),
    JURYO_SHUBETSU_CODE CHAR(1),
    KYOSO_JOKEN_CODE_2SAI CHAR(3),
    KYOSO_JOKEN_CODE_3SAI CHAR(3),
    KYOSO_JOKEN_CODE_4SAI CHAR(3),
    KYOSO_JOKEN_CODE_5SAI_IJO CHAR(3),
    KYOSO_JOKEN_CODE_SAIJAKUNEN CHAR(3),
    KYOSO_JOKEN_MEISHO VARCHAR(60),
    KYORI CHAR(4),
    HENKOMAE_KYORI CHAR(4),
    TRACK_CODE CHAR(2),
    HENKOMAE_TRACK_CODE CHAR(2),
    COURSE_KUBUN CHAR(2),
    HENKOMAE_COURSE_KUBUN CHAR(2),
    HONSHOKIN1 CHAR(8),
    HONSHOKIN2 CHAR(8),
    HONSHOKIN3 CHAR(8),
    HONSHOKIN4 CHAR(8),
    HONSHOKIN5 CHAR(8),
    HONSHOKIN6 CHAR(8),
    HONSHOKIN7 CHAR(8),
    INDEX idx_race_shosai_date (KAISAI_NEN, KAISAI_GAPPI),
    INDEX idx_race_shosai_keibajo (KEIBAJO_CODE),
    INDEX idx_race_shosai_grade (GRADE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- KYOSOBA_MASTER2（競走馬マスター）
CREATE TABLE IF NOT EXISTS KYOSOBA_MASTER2 (
    INSERT_TIMESTAMP CHAR(19),
    UPDATE_TIMESTAMP CHAR(19),
    RECORD_SHUBETSU_ID CHAR(2),
    DATA_KUBUN CHAR(1),
    DATA_SAKUSEI_NENGAPPI CHAR(8),
    KETTO_TOROKU_BANGO CHAR(10) PRIMARY KEY,
    MASSHO_KUBUN CHAR(1),
    TOROKU_NENGAPPI CHAR(8),
    MASSHO_NENGAPPI CHAR(8),
    SEINENGAPPI CHAR(8),
    BAMEI VARCHAR(36),
    BAMEI_HANKAKU_KANA VARCHAR(36),
    BAMEI_ENG VARCHAR(60),
    JRA_SHISETSU_ZAIKYU_FLAG CHAR(1),
    UMAKIGO_CODE CHAR(2),
    SEIBETSU_CODE CHAR(1),
    HINSHU_CODE CHAR(1),
    MOSHOKU_CODE CHAR(2),
    KETTO1_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO1_BAMEI VARCHAR(36),
    KETTO2_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO2_BAMEI VARCHAR(36),
    KETTO3_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO3_BAMEI VARCHAR(36),
    KETTO4_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO4_BAMEI VARCHAR(36),
    KETTO5_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO5_BAMEI VARCHAR(36),
    KETTO6_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO6_BAMEI VARCHAR(36),
    KETTO7_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO7_BAMEI VARCHAR(36),
    KETTO8_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO8_BAMEI VARCHAR(36),
    KETTO9_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO9_BAMEI VARCHAR(36),
    KETTO10_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO10_BAMEI VARCHAR(36),
    KETTO11_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO11_BAMEI VARCHAR(36),
    KETTO12_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO12_BAMEI VARCHAR(36),
    KETTO13_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO13_BAMEI VARCHAR(36),
    KETTO14_HANSHOKU_TOROKU_BANGO CHAR(10),
    KETTO14_BAMEI VARCHAR(36),
    TOZAI_SHOZOKU_CODE CHAR(1),
    CHOKYOSHI_CODE CHAR(5),
    CHOKYOSHIMEI_RYAKUSHO VARCHAR(8),
    INDEX idx_kyosoba_bamei (BAMEI),
    INDEX idx_kyosoba_birth (SEINENGAPPI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- UMAGOTO_RACE_JOHO（馬ごとレース情報）
CREATE TABLE IF NOT EXISTS UMAGOTO_RACE_JOHO (
    INSERT_TIMESTAMP CHAR(19),
    UPDATE_TIMESTAMP CHAR(19),
    RECORD_SHUBETSU_ID CHAR(2),
    DATA_KUBUN CHAR(1),
    DATA_SAKUSEI_NENGAPPI CHAR(8),
    RACE_CODE CHAR(16) NOT NULL,
    KAISAI_NEN CHAR(4),
    KAISAI_GAPPI CHAR(4),
    KEIBAJO_CODE CHAR(2),
    KAISAI_KAIJI CHAR(2),
    KAISAI_NICHIJI CHAR(2),
    RACE_BANGO CHAR(2),
    WAKUBAN CHAR(1),
    UMABAN CHAR(2),
    KETTO_TOROKU_BANGO CHAR(10) NOT NULL,
    BAMEI VARCHAR(36),
    UMAKIGO_CODE CHAR(2),
    SEIBETSU_CODE CHAR(1),
    HINSHU_CODE CHAR(1),
    MOSHOKU_CODE CHAR(2),
    BAREI CHAR(2),
    TOZAI_SHOZOKU_CODE CHAR(1),
    CHOKYOSHI_CODE CHAR(5),
    CHOKYOSHIMEI_RYAKUSHO VARCHAR(8),
    BANUSHI_CODE CHAR(6),
    BANUSHIMEI_HOJINKAKU_NASHI VARCHAR(64),
    FUKUSHOKU_HYOJI VARCHAR(60),
    FUTAN_JURYO CHAR(3),
    HENKOMAE_FUTAN_JURYO CHAR(3),
    BLINKER_SHIYO_KUBUN CHAR(1),
    KISHU_CODE CHAR(5),
    HENKOMAE_KISHU_CODE CHAR(5),
    KISHUMEI_RYAKUSHO VARCHAR(8),
    HENKOMAE_KISHUMEI_RYAKUSHO VARCHAR(8),
    KISHU_MINARAI_CODE CHAR(1),
    HENKOMAE_KISHU_MINARAI_CODE CHAR(1),
    BATAIJU CHAR(3),
    ZOGEN_FUGO CHAR(1),
    ZOGEN_SA CHAR(3),
    IJO_KUBUN_CODE CHAR(1),
    NYUSEN_JUNI CHAR(2),
    KAKUTEI_CHAKUJUN CHAR(2),
    DOCHAKU_KUBUN CHAR(1),
    DOCHAKU_TOSU CHAR(1),
    SOHA_TIME CHAR(4),
    CHAKUSA_CODE1 CHAR(3),
    CHAKUSA_CODE2 CHAR(3),
    CHAKUSA_CODE3 CHAR(3),
    CORNER1_JUNI CHAR(2),
    CORNER2_JUNI CHAR(2),
    CORNER3_JUNI CHAR(2),
    CORNER4_JUNI CHAR(2),
    PRIMARY KEY (RACE_CODE, KETTO_TOROKU_BANGO),
    INDEX idx_umagoto_ketto (KETTO_TOROKU_BANGO),
    INDEX idx_umagoto_kishu (KISHU_CODE),
    INDEX idx_umagoto_chokyo (CHOKYOSHI_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- KISHU_MASTER（騎手マスター）
CREATE TABLE IF NOT EXISTS KISHU_MASTER (
    INSERT_TIMESTAMP CHAR(19),
    UPDATE_TIMESTAMP CHAR(19),
    RECORD_SHUBETSU_ID CHAR(2),
    DATA_KUBUN CHAR(1),
    DATA_SAKUSEI_NENGAPPI CHAR(8),
    KISHU_CODE CHAR(5) PRIMARY KEY,
    MASSHO_KUBUN CHAR(1),
    MENKYOKOFU_NENGAPPI CHAR(8),
    MASSHO_NENGAPPI CHAR(8),
    SEINENGAPPI CHAR(8),
    KISHUMEI VARCHAR(34),
    KISHUMEI_KANA VARCHAR(30),
    KISHUMEI_RYAKUSHO VARCHAR(8),
    KISHUMEI_ENG VARCHAR(80),
    SEIBETSU_CODE CHAR(1),
    KIJO_SHIKAKU_CODE CHAR(1),
    KISHU_MINARAI_CODE CHAR(1),
    TOZAI_SHOZOKU_CODE CHAR(1),
    INDEX idx_kishu_name (KISHUMEI),
    INDEX idx_kishu_tozai (TOZAI_SHOZOKU_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CHOKYOSHI_MASTER（調教師マスター）
CREATE TABLE IF NOT EXISTS CHOKYOSHI_MASTER (
    INSERT_TIMESTAMP CHAR(19),
    UPDATE_TIMESTAMP CHAR(19),
    RECORD_SHUBETSU_ID CHAR(2),
    DATA_KUBUN CHAR(1),
    DATA_SAKUSEI_NENGAPPI CHAR(8),
    CHOKYOSHI_CODE CHAR(5) PRIMARY KEY,
    MASSHO_KUBUN CHAR(1),
    MENKYOKOFU_NENGAPPI CHAR(8),
    MASSHO_NENGAPPI CHAR(8),
    SEINENGAPPI CHAR(8),
    CHOKYOSHIMEI VARCHAR(34),
    CHOKYOSHIMEI_KANA VARCHAR(30),
    CHOKYOSHIMEI_RYAKUSHO VARCHAR(8),
    CHOKYOSHIMEI_ENG VARCHAR(80),
    SEIBETSU_CODE CHAR(1),
    TOZAI_SHOZOKU_CODE CHAR(1),
    INDEX idx_chokyo_name (CHOKYOSHIMEI),
    INDEX idx_chokyo_tozai (TOZAI_SHOZOKU_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BANUSHI_MASTER（馬主マスター）
CREATE TABLE IF NOT EXISTS BANUSHI_MASTER (
    INSERT_TIMESTAMP CHAR(19),
    UPDATE_TIMESTAMP CHAR(19),
    RECORD_SHUBETSU_ID CHAR(2),
    DATA_KUBUN CHAR(1),
    DATA_SAKUSEI_NENGAPPI CHAR(8),
    BANUSHI_CODE CHAR(6) PRIMARY KEY,
    BANUSHIMEI VARCHAR(64),
    BANUSHIMEI_KANA VARCHAR(100),
    BANUSHIMEI_ENG VARCHAR(100),
    HOJIN_KUBUN CHAR(1),
    INDEX idx_banushi_name (BANUSHIMEI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- コードマスターテーブル（mykeibaDB標準）
-- ========================================

-- 競馬場コードマスター
CREATE TABLE IF NOT EXISTS KEIBAJO_CODE (
    CODE CHAR(2) PRIMARY KEY,
    NAME VARCHAR(20),
    NAME_KANA VARCHAR(40)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- グレードコードマスター
CREATE TABLE IF NOT EXISTS GRADE_CODE (
    CODE CHAR(1) PRIMARY KEY,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- トラックコードマスター
CREATE TABLE IF NOT EXISTS TRACK_CODE (
    CODE CHAR(2) PRIMARY KEY,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 天候コードマスター
CREATE TABLE IF NOT EXISTS TENKO_CODE (
    CODE CHAR(1) PRIMARY KEY,
    NAME VARCHAR(10),
    DESCRIPTION VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 性別コードマスター
CREATE TABLE IF NOT EXISTS SEIBETSU_CODE (
    CODE CHAR(1) PRIMARY KEY,
    NAME VARCHAR(10),
    DESCRIPTION VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- オッズ・払戻テーブル（mykeibaDB標準）
-- ========================================

-- 単勝オッズ
CREATE TABLE IF NOT EXISTS ODDS1_TANSHO (
    RACE_CODE CHAR(16) NOT NULL,
    UMABAN CHAR(2) NOT NULL,
    ODDS_VALUE DECIMAL(6,1),
    NINKI_JUNI CHAR(2),
    UPDATE_TIME CHAR(19),
    PRIMARY KEY (RACE_CODE, UMABAN),
    FOREIGN KEY (RACE_CODE) REFERENCES RACE_SHOSAI(RACE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 複勝オッズ
CREATE TABLE IF NOT EXISTS ODDS1_FUKUSHO (
    RACE_CODE CHAR(16) NOT NULL,
    UMABAN CHAR(2) NOT NULL,
    ODDS_MIN DECIMAL(6,1),
    ODDS_MAX DECIMAL(6,1),
    UPDATE_TIME CHAR(19),
    PRIMARY KEY (RACE_CODE, UMABAN),
    FOREIGN KEY (RACE_CODE) REFERENCES RACE_SHOSAI(RACE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 払戻情報
CREATE TABLE IF NOT EXISTS HARAIMODOSHI (
    RACE_CODE CHAR(16) NOT NULL,
    BAKENSHI_KUBUN CHAR(2) NOT NULL,
    KUMIBAN VARCHAR(20) NOT NULL,
    HARAIMODOSHI_KIN INT,
    NINKI_JUNI CHAR(2),
    PRIMARY KEY (RACE_CODE, BAKENSHI_KUBUN, KUMIBAN),
    FOREIGN KEY (RACE_CODE) REFERENCES RACE_SHOSAI(RACE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- 追加分析用テーブル
-- ========================================

-- 予測結果保存用
CREATE TABLE IF NOT EXISTS PREDICTIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    RACE_CODE CHAR(16) NOT NULL,
    model_name VARCHAR(50) NOT NULL,
    model_version VARCHAR(20),
    prediction_data JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RACE_CODE) REFERENCES RACE_SHOSAI(RACE_CODE),
    INDEX idx_prediction_race_model (RACE_CODE, model_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 特徴量キャッシュ
CREATE TABLE IF NOT EXISTS FEATURE_CACHE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    RACE_CODE CHAR(16) NOT NULL,
    KETTO_TOROKU_BANGO CHAR(10) NOT NULL,
    feature_type VARCHAR(50) NOT NULL,
    feature_data JSON NOT NULL,
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    UNIQUE KEY unique_feature (RACE_CODE, KETTO_TOROKU_BANGO, feature_type),
    FOREIGN KEY (RACE_CODE) REFERENCES RACE_SHOSAI(RACE_CODE),
    FOREIGN KEY (KETTO_TOROKU_BANGO) REFERENCES KYOSOBA_MASTER2(KETTO_TOROKU_BANGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- 初期データ投入（コードマスター）
-- ========================================

-- 競馬場マスターデータ
INSERT INTO KEIBAJO_CODE (CODE, NAME, NAME_KANA) VALUES
    ('01', '札幌', 'サッポロ'),
    ('02', '函館', 'ハコダテ'),
    ('03', '福島', 'フクシマ'),
    ('04', '新潟', 'ニイガタ'),
    ('05', '東京', 'トウキョウ'),
    ('06', '中山', 'ナカヤマ'),
    ('07', '中京', 'チュウキョウ'),
    ('08', '京都', 'キョウト'),
    ('09', '阪神', 'ハンシン'),
    ('10', '小倉', 'コクラ')
ON DUPLICATE KEY UPDATE NAME=VALUES(NAME);

-- グレードコード
INSERT INTO GRADE_CODE (CODE, NAME, DESCRIPTION) VALUES
    ('0', '一般', '一般競走'),
    ('1', 'G1', 'グレード1'),
    ('2', 'G2', 'グレード2'),
    ('3', 'G3', 'グレード3'),
    ('4', 'オープン', 'オープン競走'),
    ('5', 'リステッド', 'リステッド競走')
ON DUPLICATE KEY UPDATE NAME=VALUES(NAME);

-- トラックコード
INSERT INTO TRACK_CODE (CODE, NAME, DESCRIPTION) VALUES
    ('11', '芝・左', '芝コース左回り'),
    ('12', '芝・右', '芝コース右回り'),
    ('13', '芝・直線', '芝コース直線'),
    ('21', 'ダート・左', 'ダートコース左回り'),
    ('22', 'ダート・右', 'ダートコース右回り'),
    ('23', 'ダート・直線', 'ダートコース直線')
ON DUPLICATE KEY UPDATE NAME=VALUES(NAME);

-- 天候コード
INSERT INTO TENKO_CODE (CODE, NAME, DESCRIPTION) VALUES
    ('1', '晴', '晴天'),
    ('2', '曇', '曇天'),
    ('3', '雨', '雨天'),
    ('4', '小雨', '小雨'),
    ('5', '雪', '雪'),
    ('6', '小雪', '小雪')
ON DUPLICATE KEY UPDATE NAME=VALUES(NAME);

-- 性別コード
INSERT INTO SEIBETSU_CODE (CODE, NAME, DESCRIPTION) VALUES
    ('1', '牡', '牡馬'),
    ('2', '牝', '牝馬'),
    ('3', 'セ', 'セン馬')
ON DUPLICATE KEY UPDATE NAME=VALUES(NAME);