name: Lint

on:
  push:
    branches: [ main, develop, 'feature/*', 'fix/*' ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'
  UV_VERSION: '0.4.15'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ env.UV_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-lint-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-lint-

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install -r requirements-dev.txt

    - name: Run Ruff linter
      run: |
        echo "::group::Running Ruff linter"
        uv run ruff check src/ tests/ scripts/ --output-format=github
        echo "::endgroup::"

    - name: Check code formatting with Ruff
      run: |
        echo "::group::Checking code formatting"
        uv run ruff format --check src/ tests/ scripts/
        echo "::endgroup::"

    - name: Run type checking with mypy
      continue-on-error: true
      run: |
        echo "::group::Running mypy type checker"
        uv run mypy src/ --config-file mypy.ini || echo "::warning::Type checking failed but continuing"
        echo "::endgroup::"

    - name: Check import sorting
      run: |
        echo "::group::Checking import sorting"
        uv run ruff check src/ tests/ scripts/ --select I --diff
        echo "::endgroup::"

    - name: Generate lint report
      if: failure()
      run: |
        echo "## Lint Report" > lint-report.md
        echo "" >> lint-report.md
        echo "### Ruff Check" >> lint-report.md
        uv run ruff check src/ tests/ scripts/ --statistics >> lint-report.md 2>&1 || true
        echo "" >> lint-report.md
        echo "### Format Check" >> lint-report.md
        uv run ruff format --check src/ tests/ scripts/ --diff >> lint-report.md 2>&1 || true

    - name: Upload lint report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: lint-report.md
