name: Test CI

on:
  push:
    branches: [ main, feature/github-actions-ci ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.15"
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install -r requirements-dev.txt
    
    - name: Run tests
      run: |
        uv run pytest tests/ -v --ignore=tests/integration/
    
    - name: Run linting
      run: |
        uv run ruff check src/ tests/ || true
        uv run ruff format --check src/ tests/ || true